### ISSUE TITLE
The fairness of different implementations of  MSE

### ISSUE THREAD

**Issue by liulingbo918** [PattonYu/CUFAR#1]
In this code, MSE is implemented with sklearn, i.e., `mean_squared_error(real.flatten(), pred.flatten())`
But in UrbanFM and UrbanPy,  MSE is implemented with numpy, i.e., `np.mean(np.power(real - pred, 2))`

These two implementations have different values when `real` and `pred` are 2D matrices.
And we find that the sklearn MSE  is smaller than numpy MSE  on those datasets.

**Comment by PattonYu** [comment]
Thanks for your attention and consideration.  All experimental results (including CUFAR and baselines) we reported in the paper are evaluated in the same MSE approach, so it is fair enough for comparison.

We also evaluate all models using two different implementations of MSE, and we get the same results from these two implementations.

**Comment by liulingbo918** [comment]
This seems to be the precision issue for numerical calculations.  In most cases,  these two implementations have the same MSE error, but sometimes they have a certain deviation.   Their final results are different, when the deviations of all samples are accumulated.   Please see the picture below

![image](https://user-images.githubusercontent.com/7027922/210763990-f25d5f9f-9c5e-4e50-a6e5-fa796575c53c.png)

![image](https://user-images.githubusercontent.com/7027922/210763862-bcd12de4-3bdf-448c-a19c-c803a67ed6a4.png)

![image](https://user-images.githubusercontent.com/7027922/210764174-873487b6-2dc4-4c8f-9403-d49ea33a746f.png)

Another question： why not directly use the official results of the comparison methods?
`

**Comment by PattonYu** [comment]
I do not think that such little and small deviations (e-6 or even smaller in your pic) may cause a huge difference, i.e., 0.3 MSE in the pic. Moreover, I just evaluated TaskBJ-P1, results can be found in the attached file [P1_test_results.txt](https://github.com/PattonYu/CUFAR/files/10352116/P1_test_results.txt). It shows that there is no deviation between two implementations of MSE.

For a fair comparison, we implemented all baselines and our model in the same experimental environment.

**Comment by PattonYu** [comment]
The version of dependencies is as follows:
scikit-learn 1.0.2
numpy 1.21.5

**Comment by liulingbo918** [comment]
I find the ture reason.  

I call the `np.mean(np.power(real - pred, 2))` function after  `get_MAPE(pred, real)`. 
However, the value of `real` has been modified in `get_MAPE(pred, real)`，since its arguments are reference variables.

**Comment by PattonYu** [comment]
Congrats! Please contact me if you have any problem.
